const express=require("express");
const app=express();
const errorMiddleware=require("./middleware/errors");
const cookieParser=require("cookie-parser");
const bodyParser=require("body-parser");
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: true}));
app.use(express.json());
app.use(cookieParser());
const user=require("./routes/userRoutes");
const hack=require("./routes/hackRoutes");
app.use("/api/v1",user);
app.use("/api/v1",hack);
app.use(errorMiddleware);
module.exports=app;